### ISSUE TITLE
HEDA Administrative account creation for new contact is broken

### ISSUE THREAD

**Issue by bdunnuva** [utmccombs/AffiliationSecurity#1]
After installing the package, the HEDA automatic creation of the administrative account for new contacts doesn't occur.  I had to manually create the administrative account and assign it to the contact.  After that it all works well.  Maybe there is something I missed in the setup steps?  HEDA version is 1.35.  Thank you.

**Comment by kyleschmid** [comment]
Hi Bill,

I think this may be an unrelated issue. I just installed the package in a developer edition org and the administrative account got automatically created without issue. I'd recommend checking three things:

1. Go to HEDA Settings>System and ensure that the default account model is set to Administrative
2. Go to Trigger Handlers and ensure that the record associated with the ACCT_IndividualAccounts_TDTM class is Active
3. Query the hed__Error__c object to see if the TDTM framework caught any unhandled exceptions

Let me know what you find.

Thanks,

Kyle

**Comment by bdunnuva** [comment]
Argh... I had created a sandbox so no head trigger handler records.  I'll re-install heda into the sandbox.  Thank You!

**Comment by kyleschmid** [comment]
FYI, you can also run the following line of code in execute anonymous to insert all the default trigger handlers (any non-default handlers would be deleted after doing this).

`hed.TDTM_Global_API.setTdtmConfig(hed.TDTM_Global_API.getDefaultTdtmConfig());`
